Issue #2222: Fixed primary navigation menu block not rendering as dro…
backdrop/backdrop pull request #1585
Opened 2016-09-23 01:16 UTC by jenlampton

Fixes https://github.com/backdrop/backdrop-issues/issues/2222

2016-09-23 08:52 UTC, klonos commented
@jenlampton that failure on php7 seems to be a random one. Can you please close and reopen this PR in order to restart the test? Other than that seems to work just fine 👍

2016-09-30 01:35 UTC, quicksketch requested changes

2016-09-30 01:35 UTC, quicksketch commented on core/modules/layout/layout.install
> +  $layout = layout_load('home');
Let's add a check to see if the layout is still there in the first place. `layout_load()` will return FALSE if the given layout does not exist.

2016-09-30 01:35 UTC, quicksketch commented on core/modules/layout/layout.install
> +function layout_update_1000() {
Let's try putting this update in `standard.install`, as it actually "owns" the layout configuration. Being in layout.install is also correctly breaking the upgrade tests.

2016-09-30 01:35 UTC, quicksketch commented on core/modules/layout/layout.install
> +    if ($block_info->delta == 'main-menu') {
Maybe as an extra safe check `&& empty($layout->content[$uuid]->settings['block_settings']['style'])`

2016-09-30 02:04 UTC, jenlampton commented on core/modules/layout/layout.install
> +function layout_update_1000() {
done.

2016-09-30 02:05 UTC, jenlampton commented on core/modules/layout/layout.install
> +  $layout = layout_load('home');
easy enough.

2016-09-30 02:06 UTC, jenlampton commented on core/modules/layout/layout.install
> +    if ($block_info->delta == 'main-menu') {
it's not empty, it's `default`

2016-09-30 02:39 UTC, jenlampton commented on core/modules/layout/layout.install
> +function layout_update_1000() {
Nope, it won't run there.

2016-09-30 02:40 UTC, jenlampton commented on core/modules/layout/layout.install
> +function layout_update_1000() {
oh, it helps if you are on the right branch. Yes, it runs there!

2016-09-30 02:41 UTC, jenlampton commented on core/modules/layout/layout.install
> +    if ($block_info->delta == 'main-menu') {
double checked: on a fresh install, it is empty.

2016-09-30 04:59 UTC, quicksketch requested changes

2016-09-30 04:59 UTC, quicksketch commented on profiles/standard/standard.install
> +      dvm($layout->content[$uuid]->settings['block_settings']['style']);
Remove `dvm()`. :wink:

2016-09-30 05:01 UTC, quicksketch commented on profiles/standard/standard.install
> +  if ($layout = layout_load('home')) {
Sorry I should have remembered this in the first round of feedback, but we shouldn't be using APIs like `layout_load()` in the update hook. Instead you should use config and load the file directly, e.g. `$config = config('layout.layout.home');` and then check `$config->isNew()` to see if it existed.

2016-09-30 05:12 UTC, jenlampton commented on profiles/standard/standard.install
> +      dvm($layout->content[$uuid]->settings['block_settings']['style']);
pushed.

2016-09-30 05:13 UTC, jenlampton commented on profiles/standard/standard.install
> +  if ($layout = layout_load('home')) {
okiedokie.

2016-09-30 07:19 UTC, jenlampton commented on profiles/standard/standard.install
> +  if ($layout = layout_load('home')) {
ugh, this stupid $config object is impossible to work with... are you sure I can't use $layout?

2016-09-30 07:25 UTC, jenlampton commented on profiles/standard/standard.install
> +  if ($layout = layout_load('home')) {
...think I got it.

2016-10-15 22:41 UTC, merged

2016-10-15 22:41 UTC, quicksketch commented
Thanks everyone! Merged into 1.x for 1.5.1.