Issue #2311: Basis: fix email field label and asterisks in contact form
backdrop/backdrop pull request #1629
Opened 2016-10-29 11:43 UTC by klonos

Fixes https://github.com/backdrop/backdrop-issues/issues/2311

2016-12-11 01:19 UTC, wesruv commented
I'm good with everything except removing the underline... for accessibility sake I think we should keep an underline on all elements that are using `<abbr>` element.

2016-12-11 01:20 UTC, wesruv requested changes

2016-12-11 01:20 UTC, wesruv commented on core/themes/basis/css/component/backdrop-form.css
> +    border-bottom: none;
This needs to be removed

2016-12-11 01:20 UTC, wesruv commented
Thanks for tackling this @klonos

2017-01-09 05:21 UTC, merged

2017-01-09 05:21 UTC, quicksketch commented
Merged into 1.x and 1.5.x.