Issue #2315: Link "Available updates" page to "Updates" page
backdrop/backdrop pull request #1638
Opened 2016-11-04 21:23 UTC by laryn

2016-11-15 23:37 UTC, quicksketch requested changes
Overall this looks great and is a good enhancement for UX. We just need to fix some coding standards here and I think we're good to go. :)

2016-11-15 23:37 UTC, quicksketch commented on core/modules/update/theme/update.theme.inc
> +    if (empty($status_label)) $status_label = check_plain($project['reason']);
Coding standards: We always include squiggle brackets around IF statements. https://api.backdropcms.org/php-standards#control-structures

2016-11-15 23:37 UTC, quicksketch commented on core/modules/update/theme/update.theme.inc
> +    $updatelink = ($project['name'] != 'backdrop');
Coding standards: We always separate words within a variable by an underscore, e.g. `$update_link`

2016-11-15 23:37 UTC, quicksketch commented on core/modules/update/theme/update.theme.inc
> +      $row .= l($status_label,'admin/'.$project['project_type'].'s/update',array('html' => TRUE));
Coding standards: Include a space on either side of periods when doing string concatenation. https://api.backdropcms.org/php-standards#string-concatenation

2016-11-16 17:17 UTC, laryn commented on core/modules/update/theme/update.theme.inc
> +      $row .= l($status_label,'admin/'.$project['project_type'].'s/update',array('html' => TRUE));
Thanks -- modified those now and will keep in mind going forward! Thanks for the link to the documentation, I hadn't bookmarked that before.

2018-05-27 17:49 UTC, docwilmot commented
Fixed with https://github.com/backdrop/backdrop/pull/1739

2018-05-27 17:49 UTC, closed without merging