Issue #2408: Remove message styles from Basis, and move them out of s…
backdrop/backdrop pull request #1743
Opened 2017-01-14 23:59 UTC by jenlampton

Fixes https://github.com/backdrop/backdrop-issues/issues/2408

2017-01-15 06:37 UTC, quicksketch requested changes

2017-01-15 06:37 UTC, quicksketch commented on core/modules/system/css/system.messages.css
> +@media only screen and (min-width: 600px) {
We should keep with the `em` conversions here.

2017-01-16 00:32 UTC, quicksketch approved these changes

2017-01-16 02:12 UTC, jenlampton commented
The updated commit makes it hard to tell what's been changed without an interdiff, but I pulled the branch and did a diff on the merge, and as  far as I can tell it looks like the only thing that's changed is the name of the CSS file.  If that's all it is this is RTBC from me.

2017-01-16 02:25 UTC, merged

2017-01-16 02:25 UTC, quicksketch commented
Merged into 1.x for 1.6.0.