Issue #2468: Views UI: title missing from the "Access" box.
backdrop/backdrop pull request #1753
Opened 2017-01-15 20:56 UTC by klonos

Fixes https://github.com/backdrop/backdrop-issues/issues/2468

2017-04-28 23:57 UTC, quicksketch requested changes

2017-04-28 23:57 UTC, quicksketch commented on core/modules/views/plugins/views_plugin_display.inc
> +        'title' => 'Access',
Needs a `t()` here.

2017-04-29 15:25 UTC, klonos commented
...I should have learned by now. Tsk tsk tsk 😄 Fixed.

2017-04-30 00:03 UTC, merged

2017-04-30 00:03 UTC, quicksketch commented
Thanks @klonos! Merged into 1.x and 1.6.x.