Issue #485: Slightly improved status report page (2 columns variant).
backdrop/backdrop pull request #1820
Opened 2017-03-23 13:30 UTC by klonos

Fixes https://github.com/backdrop/backdrop-issues/issues/485

Alternative to https://github.com/backdrop/backdrop/pull/1802

2017-04-22 21:22 UTC, quicksketch requested changes

2017-04-22 21:22 UTC, quicksketch commented on core/modules/system/system.theme.inc
> +  return theme_table($system_status_report_table);
Just a note, this should be `theme('table', $system_status_report_table)` to make themeable.

2017-04-22 21:22 UTC, quicksketch commented on core/modules/system/system.theme.inc
> +    'empty' => 'No status report. Something is definitely wrong.',
We can probably skip this empty text.

2017-04-22 21:22 UTC, quicksketch commented on core/includes/theme.inc
> -/**
Oops, this looks like it may be a merge issue. We shouldn't be deleting `theme_help()`.

2017-04-23 00:19 UTC, jenlampton commented
closing in favor of https://github.com/backdrop/backdrop/pull/1836

2017-04-23 00:19 UTC, closed without merging