Issue #2632: Core fieldable file entity bundles
backdrop/backdrop pull request #1924
Opened 2017-07-10 15:50 UTC by Al-Rozhkov

2017-07-10 16:22 UTC, Al-Rozhkov commented
Closing to restart sandbox

2017-07-11 10:33 UTC, Al-Rozhkov commented
Closing and reopen to fix the problem with missed Alt and Title fileds on Image bundle.

2017-10-26 20:01 UTC, quicksketch requested changes
Minor issues in my first read-through. I think we may want to reconsider the "file_metadata" table, which for core purposes really just means image width/height. I'll post more feedback to the parent issue at https://github.com/backdrop/backdrop-issues/issues/2632.

2017-10-26 20:01 UTC, quicksketch commented on core/modules/file/file.file.inc
> +  $new_mappings['webp'] = 'image/webp';
Looks like these mappings can be deleted. See d3b960e15895c5f448cb3c1b4c5d4981ab69976f.

2017-10-26 20:01 UTC, quicksketch commented on core/modules/file/file.install
> +	  'type' => array(
Minor spacing issue, remove indentation.

2020-02-01 16:36 UTC, closed without merging