2774 jen1
backdrop/backdrop pull request #2002
Opened 2017-09-10 23:18 UTC by jenlampton

PR for https://github.com/backdrop/backdrop-issues/issues/2774

2017-09-26 12:33 UTC, quicksketch requested changes
Needs a few very minor updates. Overall looks great!

2017-09-26 12:33 UTC, quicksketch commented on core/modules/update/tests/themes/update_test_admintheme/update_test_admintheme.info
> +core = 7.x
This should be `backdrop = 1.x` I believe.

2017-09-26 12:33 UTC, quicksketch commented on core/modules/update/tests/update.test
> +        'version' => '7.x-1.0',
We should update all these `version` strings to be `1.x-` instead of `7.x-`.

2018-01-02 07:05 UTC, jenlampton commented
Fixed, and rebased.

2018-01-14 22:43 UTC, quicksketch approved these changes

2018-01-14 22:43 UTC, merged

2018-01-14 22:44 UTC, quicksketch commented
Thanks @jenlampton! Merged into 1.x and 1.8.x.