Issue #2709: Consider replacing the home button with a Back to site b…
backdrop/backdrop pull request #2040
Opened 2017-11-17 23:15 UTC by alexfinnarn

…utton

2018-05-20 19:26 UTC, opi requested changes
Thanks for working on this nice UX improvment ! I noticed few stuff to fix. I'm ready to discuss and help.

2018-05-20 19:26 UTC, opi commented on core/modules/admin_bar/admin_bar.inc
> +    '#default_value' => $config->get('back_to_site'),
I like when variable name are almost self-explanatory, what about something like `backtosite_link` ?

2018-05-20 19:26 UTC, opi commented on core/modules/admin_bar/admin_bar.module
> +  $settings['current_path_is_admin'] = false;
use uppercased `TRUE` and `FALSE` constants.

2018-05-20 19:26 UTC, opi commented on core/modules/admin_bar/admin_bar.module
> +    $settings['current_path_is_admin'] = true;
could be one-lined: 
`$settings['current_path_is_admin'] = path_is_admin($settings['current_path'])`.

2018-05-20 19:26 UTC, opi commented on core/modules/admin_bar/js/admin_bar.js
> +
unnecessary line breaks

2018-05-20 19:26 UTC, opi commented on core/modules/admin_bar/admin_bar.inc
> +    '#title' => t('Add Back To Site Link'),
should be lowercased, as @BWPanda said in his [review](https://github.com/backdrop/backdrop-issues/issues/2709#issuecomment-390500108)

2022-12-02 22:53 UTC, quicksketch commented
Replaced by https://github.com/backdrop/backdrop/pull/4236. Thanks @alexfinnarn!

2022-12-02 22:53 UTC, closed without merging