Issue #260: Redirect to user/login when anonymous views user page.
backdrop/backdrop pull request #2052
Opened 2017-12-30 18:48 UTC by quicksketch

Fixes backdrop/backdrop-issues#260

Replaces https://github.com/backdrop/backdrop/pull/752.

2017-12-30 19:48 UTC, opi requested changes

2017-12-30 19:48 UTC, opi commented on core/includes/theme.maintenance.inc
> +  backdrop_add_css($path . '/css/messages.theme.css', array('group' => CSS_SYSTEM, 'every_page' => TRUE));
Unrelated change, this PR should be rebased ;)

2018-01-01 18:44 UTC, quicksketch commented
Thanks @opi! Rerolled to remove that unrelated change to theme.maintenance.inc and also fixed the remaining failing test.

2018-01-05 07:50 UTC, opi approved these changes
tested, works perfectly as expected.

2018-01-12 20:19 UTC, merged

2018-01-12 20:19 UTC, serundeputy commented
Thanks @opi @jenlampton and @quicksketch !

Works as expected merged into `1.x` for `1.9.0.`!