Issue #2990: Settings form for contact module.
backdrop/backdrop pull request #2105
Opened 2018-02-27 19:03 UTC by opi

Still Work-In-Progress !

I need some help on the wording part, from a native english speaker

2018-02-28 13:21 UTC, opi commented
close+reopen to re-run the tests

2018-02-28 15:25 UTC, oadaeh reviewed
Here is what I noticed.

2018-02-28 15:25 UTC, oadaeh commented on core/modules/contact/contact.admin.inc
> +    '#description' => t("Allow users to send themselves a copy on site-wide and personnal contact form"),
The word "personal" only has one "n".
I think it is not necessary to have the "on site-wide and personnal contact form" part, as that is what the setting is for.
However, I think adding something like "of their message" would not be a bad idea.
Also, it needs a period at the end.
So, something like this: "Allow users to send themselves a copy of their message."

2018-02-28 15:25 UTC, oadaeh commented on core/modules/contact/contact.module
> + * Show the personnal copy checkbox on forms
The word "personal" only has one "n", and the sentence should end with a period.
I think this wording better defines the function: Determines if the 'Send yourself a copy' checkbox should be shown.

2018-04-24 08:41 UTC, opi commented
@oadaeh thanks, your concerns were addressed.

2018-05-15 08:42 UTC, opi commented
closing to refresh the sandbox

2018-05-17 09:11 UTC, opi commented
closing to refresh the sandbox

2018-05-17 18:10 UTC, mikemccaffrey commented on core/modules/contact/contact.admin.inc
> +    '#description' => t("Allow users to send themselves a copy on site-wide and personnal contact form"),
Sentence should end with a period.

2018-05-23 23:13 UTC, quicksketch requested changes
Minor docs and naming updates. As an entirely new form and page, I think we should pend this for 1.11.0 and we need to document that in the form function docblock.

2018-05-23 23:13 UTC, quicksketch commented on core/modules/contact/contact.module
> +function contact_show_personnal_copy_checkbox() {
Same spelling issue here. `personnal` should only have a single `n`.

2018-05-23 23:13 UTC, quicksketch commented on core/modules/contact/contact.admin.inc
> + * Page callback: Contact settings.
As a form, this shouldn't be described as a page callback. Simply "Contact settings form." is sufficient.

2018-05-23 23:13 UTC, quicksketch commented on core/modules/contact/contact.admin.inc
> + * @see contact_menu()
Let's include both the following:

```
@ingroup forms
@since 1.11.0
```

2018-05-24 08:27 UTC, opi commented
run tests again

2018-06-14 22:32 UTC, quicksketch approved these changes

2018-06-14 22:36 UTC, quicksketch commented
All tests are passing and this implementation look great! I did one more minor spelling change, otherwise everything looks great. Merged into 1.x for 1.11.0. Thanks @opi!

2018-06-14 22:37 UTC, merged