Issue #3002: [UX] Improvements to pathauto bulk-update page
backdrop/backdrop pull request #2233
Opened 2018-06-29 18:47 UTC by klonos

https://github.com/backdrop/backdrop-issues/issues/3002

2018-06-29 21:11 UTC, opi requested changes

2018-06-29 21:11 UTC, opi commented on core/modules/path/path.admin.inc
> +        '#title' => $path_info['alias bulk actions description'],
`alias bulk actions description` is a new required key for https://api.backdropcms.org/api/backdrop/core%21modules%21path%21path.api.php/function/hook_path_info/1 , so maybe this is an API break.
At least hook_path_info documentation must be updated in https://github.com/backdrop/backdrop/blob/1.x/core/modules/path/path.api.php#L104

2018-06-29 21:11 UTC, opi commented on core/modules/path/path.admin.inc
> +      if (isset($path_info['alias bulk actions items'])) {
same here

2018-06-30 09:08 UTC, opi commented on core/modules/path/path.api.php
> + *   - alias bulk actions description: The translated label for the checkboxes
Nice. You may add the `alias bulk actions items` key too

2018-09-01 04:39 UTC, quicksketch commented on core/modules/path/path.path.inc
> +    $info['taxonomy_term']['alias bulk actions items'][$vocabulary_name] = t('URL alias for <strong>%vocabulary_label</strong> <small>(Machine name: <code>!machine_name</code>)</small>', array('%voca
Needs another two spaces indentation.

2018-09-22 12:34 UTC, opi commented
rerolled https://github.com/backdrop/backdrop/pull/2310

2018-09-22 12:34 UTC, opi commented
can we close this PR ?

2018-11-05 19:27 UTC, klonos commented
...yep, sorry for the late response @opi 

Closing in favour of https://github.com/backdrop/backdrop/pull/2310

2018-11-05 19:27 UTC, closed without merging