Issue #3311: [DX][Docs] Update the API documentation to include the new 'info' type for messages.
backdrop/backdrop pull request #2317
Opened 2018-10-12 03:19 UTC by klonos

https://github.com/backdrop/backdrop-issues/issues/3311

2018-10-19 07:19 UTC, opi requested changes

2018-10-19 07:19 UTC, opi commented on core/includes/bootstrap.inc
> + * @param string $message
redundant

2018-10-19 07:19 UTC, opi commented on core/includes/bootstrap.inc
> + *   (optional) The type of the message. Defaults to 'status'. These values are
Not sure about informal tone in documentation. I personnaly don't mind, but we should be consistant across the whole documentation.

2018-10-20 00:24 UTC, klonos commented on core/includes/bootstrap.inc
> + *   (optional) The type of the message. Defaults to 'status'. These values are
...oops 😅...fixed!

2018-10-20 00:25 UTC, klonos commented on core/includes/bootstrap.inc
> + *   (optional) The type of the message. Defaults to 'status'. These values are
Yep, not sure either. That's why I am asking for feedback.

2019-04-14 11:44 UTC, klonos commented
Closing in favor of https://github.com/backdrop/backdrop/pull/2575

2019-04-14 11:44 UTC, closed without merging