Issue #3331: [UX] Modules page: Modernize the error icon for incompatible modules
backdrop/backdrop pull request #2331
Opened 2018-10-20 03:06 UTC by klonos

https://github.com/backdrop/backdrop-issues/issues/3331

2018-10-23 04:21 UTC, herbdool commented
Looks better than before.

2018-11-30 01:21 UTC, quicksketch requested changes

2018-11-30 01:21 UTC, quicksketch commented on core/modules/system/system.admin.inc
> +        'class' => array('modules-error', 'error'),
Rather than using a container (fancy word for `div`), seems like this would be easier/preferable to just use `#markup` and write this all as a span? `'<span class="modules-error"><span class="element-invisible">' . $title . '</span><span>'`;

2018-11-30 01:21 UTC, quicksketch commented on core/modules/system/css/system.admin.css
> +}
Why add the `error` class if we're just going to undo it's background? Seems like we could just drop it from the markup.

2018-11-30 01:21 UTC, quicksketch commented on core/modules/system/css/system.admin.css
> +#system-modules div.modules-error:before {
Use less-specific selectors (I know this file is riddled with them) and drop the `div` element. `#system-modules .modules-error`

2018-11-30 19:08 UTC, klonos commented on core/modules/system/system.admin.inc
> +        'class' => array('modules-error', 'error'),
Done...

2018-11-30 19:08 UTC, klonos commented on core/modules/system/css/system.admin.css
> +}
...done

2018-11-30 19:09 UTC, klonos commented on core/modules/system/css/system.admin.css
> +#system-modules div.modules-error:before {
...and done 😄

2019-08-13 19:41 UTC, klonos commented
...been a while. Lets see if things still work.

2019-08-13 23:33 UTC, klonos commented
...CI is acting up again.

2019-09-01 05:33 UTC, quicksketch approved these changes

2019-09-01 05:36 UTC, merged

2019-09-01 05:37 UTC, quicksketch commented
Looks great, tried it out and the icon shows as expected. Merged into 1.x and 1.13.x. Thanks!