Issue #3627: Add a new, optional footer variable in theme_table() that produces tfoot
backdrop/backdrop pull request #2554
Opened 2019-03-28 08:37 UTC by klonos

https://github.com/backdrop/backdrop-issues/issues/3627

Credits for this should go to @drupol

2019-03-28 08:38 UTC, drupol commented
Thanks !!!

2019-03-28 09:32 UTC, klonos commented
The PR sandbox failed to build:

![Screen Shot 2019-03-28 at 8 32 00 pm](https://user-images.githubusercontent.com/2423362/55146388-98af1280-5198-11e9-9512-6f7c7005de5b.png)

Refreshing...

2019-03-28 12:20 UTC, drupol requested changes

2019-03-28 12:20 UTC, drupol commented on core/includes/theme.inc
> +      $output .= "<" . $tag . ">\n";
We should use single quote.

2019-03-28 12:25 UTC, drupol commented on core/includes/theme.inc
> +      $output .= "<" . $tag . ">\n";
```suggestion
      $output .= '<' . $tag . ">\n";
```

2019-03-28 12:55 UTC, drupol commented on core/includes/theme.inc
> +      $output .= "<" . $tag . ">\n";
I'm not sure about keeping those `\n` in there... what do you think ?

2022-07-03 10:40 UTC, indigoxela commented
This has been fixed in https://github.com/backdrop/backdrop-issues/issues/5042, closing as outdated.

2022-07-03 10:40 UTC, closed without merging