Issue #1417: User URL alias not applied to admin user out of the box.
backdrop/backdrop pull request #3241
Opened 2020-08-13 16:33 UTC by klonos

2020-09-06 08:54 UTC, klonos commented
Sandbox refresh...

2021-12-23 23:08 UTC, BWPanda commented
@klonos Care to update this PR?

2021-12-23 23:35 UTC, klonos commented
Done @BWPanda 👍🏼

2021-12-23 23:57 UTC, BWPanda requested changes
Few suggested changes for simplification.

2021-12-23 23:57 UTC, BWPanda commented on core/modules/user/tests/user_views_handler_field_name.test
> +    $user_path = $user->path['alias'] ? $user->path['alias'] : 'user/' . $user->uid;
```suggestion
    $user_id = 1;
    $user = user_load($user_id);
    $user_path = $user->path['alias'] ? $user->path['alias'] : 'user/' . $user_id;
```

2021-12-23 23:57 UTC, BWPanda commented on core/modules/user/user.install
> +  }
```suggestion
  if (module_exists('path') && config_get('path.settings', 'user_pattern')) {
    $admin_user = user_load(1);
    if ($admin_user->path['auto'] == FALSE) {
      $admin_user->path['auto'] = TRUE;
      user_save($admin_user);
    }
  }
```

2021-12-24 06:20 UTC, klonos commented on core/profiles/standard/standard.install
> +  // Assign user 1 the "Administrator" role, and make sure that generation of
```suggestion
  // Assign the "Administrator" role to user 1, and make sure that generation of
```

2021-12-24 06:32 UTC, BWPanda approved these changes

2021-12-27 05:18 UTC, merged

2021-12-27 05:18 UTC, quicksketch commented
Merged into 1.x and 1.20.x. Thanks @klonos and @BWPanda!