Issue #4203: add hover-over and focus indication to the delete/edit/r…
backdrop/backdrop pull request #3333
Opened 2020-09-27 22:50 UTC by ArchanaAnand0212

Making css changes for issue: https://github.com/backdrop/backdrop-issues/issues/4203

2020-09-30 03:44 UTC, stpaultim commented
Fixes backdrop/backdrop-issues#4203

2020-09-30 04:08 UTC, BWPanda requested changes
Just a few changes needed based on our [coding standards](https://api.backdropcms.org/css-standards).

2020-09-30 04:08 UTC, BWPanda commented on core/themes/basis/css/component/comment.css
Since this new ruleset and the previous one are related, we don't need a blank line between them.

2020-09-30 04:08 UTC, BWPanda commented on core/themes/basis/css/component/comment.css
> +.comment-footer .links.inline a:hover{
Please add a space between the selector and the opening curly bracket (`{`).

2020-09-30 04:49 UTC, stpaultim commented
@ArchanaAnand0212 - I just sent you a message in Slack, but let me post it here. Normally, every PR triggers a build of Backdrop CMS to test this PR and it runs automated tests. Neither of these things happened here, we are not sure why. 

Could you please close and then reopen this PR. You should be able to do that on this page. Hopefully that will trigger a rebuild. If not, we'll do our best to debug the situation.

2020-09-30 04:58 UTC, stpaultim commented
Ah that is much better.

Now anyone can review the work and make comments without having to spin up a test site locally.

2020-09-30 05:32 UTC, BWPanda approved these changes

2023-10-10 02:54 UTC, merged

2023-10-10 02:56 UTC, quicksketch commented
Thanks @ArchanaAnand0212 for making this pull request! It's been good for a long time but we got stuck in the review process. Now that this has been reviewed and approved I have merged this into 1.x and 1.26.x. Sorry this took so long. We appreciate your help!