Fixed document for adding keys with fields
backdrop/backdrop pull request #3651
Opened 2021-06-20 06:27 UTC by nzare

Fixes https://github.com/backdrop/backdrop-issues/issues/3759

2021-06-24 07:01 UTC, BWPanda requested changes

2021-06-24 07:01 UTC, BWPanda commented on core/includes/database/database.inc
>   *   db_change_field() for more explanation why.
We should make sure this adheres to the 80-character limit...

```suggestion
 *   Optional. An array containing the specification for keys and indexes to be 
 *   created on the table along with the field. The format is the same as a
 *   schema definition, but without the 'columns' element. If you are adding a
 *   'serial' type field, you MUST specify at least one key or index in this
 *   array. See db_change_field() for more explanation why.
```

2021-06-25 07:31 UTC, BWPanda approved these changes

2021-07-08 04:19 UTC, merged

2021-07-08 04:20 UTC, quicksketch commented
Thanks for the PR @nzare! I have merged this into 1.x and 1.19.x.