Issue #5163: Allow enabling modules/themes via config
backdrop/backdrop pull request #3692
Opened 2021-08-20 21:51 UTC by klonos

Fixes https://github.com/backdrop/backdrop-issues/issues/5163

2025-07-18 10:54 UTC, yorkshire-pudding requested changes
@quicksketch - I've reviewed the changes and they all mostly make sense.  I've suggested a change which fixes an error and should fix the tests.

I've tested with some basic modules, but will do some more testing and will benefit from wider testing.

2025-07-18 10:54 UTC, yorkshire-pudding commented on core/includes/theme.inc
> +  watchdog('system', '%theme theme enabled.', array('%theme' => $theme), WATCHDOG_INFO);
```suggestion
```

2025-07-18 10:54 UTC, yorkshire-pudding commented on core/includes/theme.inc
>    }
```suggestion
    $config->set('themes', $themes_in_config);
    $config->save();
 
    watchdog('system', '%theme theme enabled.', array('%theme' => $theme), WATCHDOG_INFO);
  }
```

2025-07-18 20:29 UTC, quicksketch commented on core/includes/config.inc
> +function config_get_default_config_names($project) {
I separated this out from `config_install_default_config()` since I needed this same functionality in the test coverage. See `ModuleTestCase::assertModuleConfigExists()`.

2025-08-15 15:10 UTC, herbdool commented on core/modules/system/system.install
> +      if (!empty($extension['info']['hidden'])) {
We should test this with `ubercart` since it uses hidden modules in an unusual way. This would put ubercart sub-modules into the extensions file - like `cart` but would skip the mother module: `ubercart`.

2025-08-15 18:55 UTC, quicksketch commented on core/modules/system/system.install
> +      if (!empty($extension['info']['hidden'])) {
Good idea. I think it would be fine with hidden modules as long as some of the shown modules list the hidden modules as dependencies.

Separately, I think hidden modules _can_ be enabled via config, but they're not automatically included in the config file. If you were to manually put a module in the staging config file and then import it, it should work. Both these scenarios could use manual and automatic testing.

2025-08-21 19:36 UTC, herbdool commented on core/modules/system/system.install
> +      if (!empty($extension['info']['hidden'])) {
In my manual testing with ubercart this is working fine.

2025-08-23 22:38 UTC, merged

2025-08-23 22:38 UTC, quicksketch commented
Merged into 1.x for 1.32.0. Thank you @herbdool and @yorkshire-pudding for the reviews here!