Issue #3888: Remove menu item when Dashboard module is disabled
backdrop/backdrop pull request #3763
Opened 2021-09-30 04:22 UTC by klonos

Fixes https://github.com/backdrop/backdrop-issues/issues/3888

2022-06-24 22:10 UTC, BWPanda requested changes

2022-06-24 22:10 UTC, BWPanda commented on core/modules/dashboard/dashboard.install
> +  $link = db_query("SELECT * FROM {menu_links} WHERE router_path LIKE 'admin/dashboard' AND module = 'system' AND hidden = 1")->fetchAssoc();
It seems you're only using the mlid here, so probably best to just return that field rather than all of them...

2022-06-24 22:10 UTC, BWPanda commented on core/modules/dashboard/dashboard.install
> +  $link = db_query("SELECT * FROM {menu_links} WHERE router_path LIKE 'admin/dashboard' AND module = 'system' AND hidden = 0")->fetchAssoc();
Same here.

2026-09-11 15:35 UTC, swampopus commented on core/modules/dashboard/dashboard.install
> +  $link = db_query("SELECT * FROM {menu_links} WHERE router_path LIKE 'admin/dashboard' AND module = 'system' AND hidden = 1")->fetchAssoc();
They are using more than the mlid from the table, so this is fine. Resolving comment.

2026-09-11 15:35 UTC, swampopus commented on core/modules/dashboard/dashboard.install
> +  $link = db_query("SELECT * FROM {menu_links} WHERE router_path LIKE 'admin/dashboard' AND module = 'system' AND hidden = 0")->fetchAssoc();
They are using more than the mlid from the table, so this is fine. Resolving comment.

2026-09-11 15:36 UTC, swampopus approved these changes
This code looks good to me.

2026-09-11 15:47 UTC, yorkshire-pudding commented
Closing and re-opening to initiate tests.

2026-09-11 15:58 UTC, yorkshire-pudding commented on core/modules/dashboard/dashboard.install
> +  $link = db_query("SELECT * FROM {menu_links} WHERE router_path LIKE 'admin/dashboard' AND module = 'system' AND hidden = 1")->fetchAssoc();
Actually, `mlid` is the only thing used from the database. The other fields are from `menu_link_load`

2026-09-11 15:59 UTC, yorkshire-pudding commented on core/modules/dashboard/dashboard.install
> +  $link = db_query("SELECT * FROM {menu_links} WHERE router_path LIKE 'admin/dashboard' AND module = 'system' AND hidden = 0")->fetchAssoc();
Actually, `mlid` is the only thing used from the database. The other fields are from `menu_link_load`

2026-09-11 16:28 UTC, swampopus commented on core/modules/dashboard/dashboard.install
> +  $link = db_query("SELECT * FROM {menu_links} WHERE router_path LIKE 'admin/dashboard' AND module = 'system' AND hidden = 1")->fetchAssoc();
Ah, right.

2026-09-11 16:44 UTC, swampopus commented
Okay-- I created a new PR to make the code changes (I couldn't figure out how to suggest specific code changes here).
New PR: https://github.com/backdrop/backdrop/pull/5334

2026-09-11 16:47 UTC, closed without merging