Fixes issue #5371
backdrop/backdrop pull request #3836
Opened 2021-11-25 16:52 UTC by argiepiano

Fixes [#5371](https://github.com/backdrop/backdrop-issues/issues/5371)

2021-11-25 18:34 UTC, klonos commented on core/modules/file/file.admin.inc
> +  $settings = isset($form_state['values']['display']['settings'][$formatter]) ? $form_state['values']['display']['settings']: array();
```suggestion
  $settings = isset($form_state['values']['display']['settings'][$formatter]) ? $form_state['values']['display']['settings'] : array();
```

2021-11-25 18:35 UTC, klonos requested changes
LGTM, besides that missing space there, before the `:` in the shorthand conditional.

2021-11-25 19:18 UTC, klonos approved these changes
LGTM now 👍🏼

2021-12-03 22:02 UTC, merged

2021-12-03 22:02 UTC, quicksketch commented
Looks great! Merged into 1.x and 1.20.x.