Issue #6303: Update the part in the documentation comment about array_filter
backdrop/backdrop pull request #4589
Opened 2023-12-01 13:49 UTC by kiamlaluno

Fixes https://github.com/backdrop/backdrop-issues/issues/6303

2025-08-04 19:54 UTC, yorkshire-pudding requested changes
I found this as was trying to understand the meaning of this cryptic comment in the function docs. I've proposed a small explanation in the code comment.

2025-08-04 19:54 UTC, yorkshire-pudding commented on core/modules/system/system.module
> +    // pass the form state values to array_filter().
Proposing a bit of extra explanation to make it clear what will happen as no callback is passed to the `array_filter()` function.

```suggestion
    // For compatibility with Drupal 7, if $form['array_filter'] is set, pass
    // the form state values to array_filter(). This will remove any empty
    // values.
```

2025-08-04 21:32 UTC, yorkshire-pudding approved these changes
Looks good

2025-08-31 07:41 UTC, merged

2025-08-31 07:42 UTC, quicksketch commented
Looks great, thanks @avpaderno! I am sorry this simple docs update took so long. Thank you @yorkshire-pudding for the review! You made it happen. Merged into 1.x and 1.31.x.